# Generated by Django 4.2.5 on 2023-09-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDER PLACED', 'Order Placed'), ('PENDING CONFIRMATION', 'Pending Confirmation'), ('WAITING TO BE SHIPPED', 'Waiting to Be Shipped'), ('SHIPPED', 'Shipped'), ('OUT FOR DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], max_length=50),
        ),
    ]
